rm(list = ls())
library(dplyr)
library(data.table)
library(tidyr)
library(ggplot2)
library(forecast)
library(plotly)
library(corrplot)
library(lme4)


# required functions
man_mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}


#setwd("")
cp <- fread('/Users/chenlu/Desktop/cleaned_data.csv', stringsAsFactors = FALSE)
cp$Date_time <- as.POSIXct(cp$Date_time, "%Y-%m-%d %H:%M:%S", tz=Sys.timezone())

cp <- cp %>% mutate(month = format(Date_time, '%b'),
                    day = format(Date_time, '%a'),
                    hour = format(Date_time, '%H'),
                    price = Gross.Sales / Qty,
                    ym = format(Date_time, '%Y-%m'))

# The first step to identify loyalty among customers is to determine the share of sales
# generated through repeating customers. Based on Pareto's 80-20 rule, we expect majority share of the sales to be
# driven by a small proportion of the customers who pay repeated visit to our store

# Keeping only the customer data that has a customer id associated to it and then determining various customer
# metrics such as lifetime purchase and tenure (day of last transaction - day of first transaction) of the customer

loyalty <- cp %>% filter(!is.na(Customer.ID)) %>% group_by(Customer.ID) %>% 
  summarise(first_purchase = min(Date_time),
            last_purchase = max(Date_time),
            distinct_trans = n_distinct(Date_time),
            lifetime_net = sum(Net.Sales),
            lifetime_purs = sum(Qty)) %>% 
  mutate(tenure = as.Date(last_purchase,  '%Y-%m-%d')  - as.Date(first_purchase, '%Y-%m-%d'),
         avg_trans = lifetime_net / distinct_trans)

# Initially we will check the share of sales by customers:
# 1. That have a customer ID
# 2. That have visited more than once
# as compared to the overall sales across 3 years:

print(paste('The % share of registered customers that have visited more than once is: ',
            round(nrow(loyalty[which(loyalty$tenure > 0),]) / nrow(loyalty) * 100, 2)))

print(paste('The % share of net sales by just 22% of registered customers is: ',
            round(sum(loyalty[which(loyalty$tenure > 0), 'lifetime_net']) / sum(cp$Net.Sales) * 100, 2)))

# About 43% of net sales over 3 years are being driven by jus 22% of registred customers who have visited more than
# once

loyalty <- data.frame(loyalty)
print(paste('The % share of total transactions driven by 22% of registered customers is: ',
            round(nrow(cp[which(cp$Customer.ID %in% loyalty[which(loyalty$tenure > 0), 'Customer.ID']),]) / nrow(cp) * 100, 2)))

# Hence we can conclude that a large number of transactions and sales are being generated by small number of customers
# by which we can safely assume presence of loyal customers

loyalty <- filter(loyalty, tenure > 0)
# Looking at the distribution of tenure of the customers
ggplot(loyalty, aes(x = tenure)) +
  geom_histogram(binwidth = 5, color = 'yellow', fill = 'maroon') +
  ggtitle('Distribution of customers based on tenure') + xlab('Tenure') + ylab('No. of customers')

# We can observe that a significant portion of the customers have tenure greater than about a month (30 days)

# Looking at the cumulative sales share based on share of customers visiting more than once
loyalty <- loyalty %>% arrange(-lifetime_net) %>% 
  mutate(cumshare = 100 * cumsum(lifetime_net) / sum(cp$Net.Sales))

ggplot(loyalty, aes(x = seq(1, nrow(loyalty)), y = cumshare)) +
  geom_line(size = 1, color = 'steelblue')+
  ggtitle('Cumulative sales share by revsiting customers') + xlab('Customers') + ylab('Share of total sales')

# Hence we based on the saturation of the curve we can deduce that Central perk has a loyal customer base of
# about 4K customers

# Finally we would like to see trend in tenure vs transactions.

ggplot(loyalty[which(loyalty$distinct_trans <= 100), ], aes(x = tenure, y = distinct_trans)) +
  geom_point(alpha = 0.5, color = 'yellow', fill = 'maroon', pch = 21) +
  geom_smooth(formula = y ~ x, method = 'lm', se = TRUE)+
  ggtitle('Distribution of days visited against tenure') + xlab('Tenure') + ylab('Days visited')

# The general pattern of visits against tenure shows increasing pattern which indicates
# that the loyal customers tend to vsit repeatedly over time

loyalty$trans_pd <- as.numeric(loyalty$tenure) / loyalty$distinct_trans
ggplot(loyalty, aes(x = trans_pd)) +
  geom_histogram(fill = 'maroon', color = 'yellow')+
  ggtitle('Distribution of average number of days beteen visits') +
  xlab('Average days between visits') + ylab('No. of customers')

# From here, it can be concluded that high number of loyal customers have up to 100 days of gap
# between subseqent visits. Hence, we have decent chunk of loyal customers

# For additional insights we can check the change in average spends per transaction based on tenure
ggplot(loyalty, aes(x = tenure, y = avg_trans)) +
  geom_point(alpha = 0.5, color = 'yellow', fill = 'maroon', pch = 21) +
  geom_smooth(formula = y ~ x, method = 'lm', se = TRUE)+
  ggtitle('Average spends based on tenure') + xlab('Tenure') + ylab('Average spends per transaction')

# Hence we observe that the spending pattern per transaction does not change significantly of
# time for repeatng customers

# Customers can churn over period but we want to ensure that our customer base consistently has certain 
# portion of loyal cusomer base retained hence we would like to check overall population of the loyal customers
# over time, In order to get this metric, we will check number of repeating customers month on month

mom <- cp %>% group_by(Customer.ID) %>% summarise(ym = min(ym))
mom <- na.omit(mom)
mom_trend <- unique(cp[, c('ym', 'Customer.ID')])
mom_trend <- na.omit(mom_trend)
mom$cust <- 'new'
mom_trend <- merge(mom_trend, mom, all.x = TRUE)
mom_trend[which(is.na(mom_trend$cust)), 'cust'] <- 'old'
mom_trend <- mom_trend %>% group_by(ym, cust) %>% summarise(count = n())
ggplot(mom_trend, aes(x = ym, y = count, group = cust, color = cust)) +
  geom_line(size = 1.5) +
  ggtitle('New vs revisiting customers over time') + xlab('Year-Month') + ylab('No. of customers') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

# Here we can ignore the dip in last month since the data is incomplete but we can obsrve that
# Overall repeating customers stay constant and even show a slight icreasing trend even though the 
# number of new customers fluctuates, hence we can say that Central Perk has a constant moving customer base
# with loyalty over specific time period keeping the overall number of repeating customers constant


# Hence we can safely assume that loyalty among customers exists. Further insights about the loyal customers can
# be found out through clustering
